title: Avocado Planet
description: Tech blog on AI, ServiceNow, and cloud engineering

url: https://avocado-planet.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: /blog
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about

social:
    github: avocado-planet
    linkedin: in/%E6%9C%8B-%E5%BC%B5-a77984179

